import type { ExecutionLine, RouteCandidate, Vault } from "./types";

export const vaults: Vault[] = [
  {
    id: "usdc-eth",
    name: "USDC-ETH",
    protocol: "Uniswap V3",
    network: "Arbitrum",
    apy: "32.41%",
    estGas: "$4.12",
    dailyYield: "+$124.50",
    riskTier: "Low",
    breakEven: "1.2 DAYS",
    breakEvenWidth: "85%",
    status: "V4_ACTIVE",
    statusTone: "accent",
    summary:
      "Tight spreads, low overhead, and a favorable recovery window make this the most efficient pair to cycle into during the next 24 hours.",
    analysisTitle: "Break-even reached in 32.4 hours",
    confidence: "98.2%",
    netApr: "14.82%",
    overheadUsd: "$84.12",
  },
  {
    id: "arb-usdc",
    name: "ARB-USDC",
    protocol: "GMX V2",
    network: "Arbitrum",
    apy: "68.19%",
    estGas: "$12.80",
    dailyYield: "+$412.02",
    riskTier: "High",
    breakEven: "3.8 DAYS",
    breakEvenWidth: "62%",
    status: "VOLATILE",
    statusTone: "muted",
    summary:
      "Higher emissions offset the cost profile, but the position remains sensitive to short-term volatility and fast liquidity rotation.",
    analysisTitle: "Reward spike likely within 48 hours",
    confidence: "91.4%",
    netApr: "27.04%",
    overheadUsd: "$142.90",
  },
  {
    id: "eth-lst",
    name: "ETH-LST",
    protocol: "Lido Finance",
    network: "Ethereum",
    apy: "4.82%",
    estGas: "$45.10",
    dailyYield: "+$18.44",
    riskTier: "Floor",
    breakEven: "12.4 DAYS",
    breakEvenWidth: "15%",
    status: "STABLE",
    statusTone: "accent",
    summary:
      "A conservative yield leg with slower cost recovery, appropriate as a ballast position rather than an active rebalance target.",
    analysisTitle: "Amortization extends beyond 12 days",
    confidence: "99.1%",
    netApr: "3.74%",
    overheadUsd: "$231.40",
  },
  {
    id: "wbtc-eth",
    name: "WBTC-ETH",
    protocol: "Curve Finance",
    network: "Mainnet",
    apy: "12.90%",
    estGas: "$24.15",
    dailyYield: "+$58.30",
    riskTier: "Mid",
    breakEven: "5.2 DAYS",
    breakEvenWidth: "45%",
    status: "BLUE_CHIP",
    statusTone: "muted",
    summary:
      "Deep liquidity and stable liquidity mining make this pair robust, but mainnet gas reduces tactical agility.",
    analysisTitle: "Mainnet cost floor limits rapid cycling",
    confidence: "95.8%",
    netApr: "8.12%",
    overheadUsd: "$160.70",
  },
  {
    id: "sol-usdc",
    name: "SOL-USDC",
    protocol: "Raydium",
    network: "Solana",
    apy: "94.10%",
    estGas: "$0.02",
    dailyYield: "+$892.40",
    riskTier: "Ultra",
    breakEven: "0.4 DAYS",
    breakEvenWidth: "98%",
    status: "HIGH_FEE",
    statusTone: "accent",
    summary:
      "The highest velocity candidate in the book, with negligible transaction drag and aggressive reward capture opportunities.",
    analysisTitle: "Break-even nearly immediate",
    confidence: "88.7%",
    netApr: "41.22%",
    overheadUsd: "$12.34",
  },
  {
    id: "op-eth",
    name: "OP-ETH",
    protocol: "Velodrome",
    network: "Optimism",
    apy: "22.50%",
    estGas: "$2.10",
    dailyYield: "+$72.15",
    riskTier: "Med-Low",
    breakEven: "2.1 DAYS",
    breakEvenWidth: "75%",
    status: "LIQUIDITY_MINING",
    statusTone: "muted",
    summary:
      "Low transaction cost and acceptable emissions create a strong secondary route for opportunistic execution bursts.",
    analysisTitle: "Balanced route for low-friction deployment",
    confidence: "96.3%",
    netApr: "16.43%",
    overheadUsd: "$51.66",
  },
];

export const routeCandidates: RouteCandidate[] = [
  {
    id: "arb-fastpath",
    label: "Arbitrum Fast Path",
    chain: "Arbitrum",
    latency: "14ms",
    cost: "$4.12",
    confidence: "98%",
    delta: "+$42/day",
    path: "USDC -> ETH -> Camelot Vault",
  },
  {
    id: "mainnet-shield",
    label: "Mainnet Shield",
    chain: "Ethereum",
    latency: "41ms",
    cost: "$24.15",
    confidence: "95%",
    delta: "+$18/day",
    path: "USDC -> WETH -> Curve LP",
  },
  {
    id: "sol-velocity",
    label: "Solana Velocity",
    chain: "Solana",
    latency: "9ms",
    cost: "$0.02",
    confidence: "89%",
    delta: "+$77/day",
    path: "USDC -> SOL -> Raydium Farm",
  },
];

export const executionLines: ExecutionLine[] = [
  { id: "line-1", tone: "muted", text: "[09:42:01] INITIALIZING_HANDSHAKE..." },
  { id: "line-2", tone: "muted", text: "[09:42:02] RESOLVING_ENDPOINTS..." },
  {
    id: "line-3",
    tone: "accent",
    text: "> Fetching gas prices from ETH_MAINNET...",
  },
  {
    id: "line-4",
    tone: "accent",
    text: "> Optimal gas found: 18.4 Gwei",
  },
  {
    id: "line-5",
    tone: "success",
    text: "✓ Allowance transaction 0x72a...912 confirmed",
  },
  {
    id: "line-6",
    tone: "muted",
    text: "[09:42:15] CALCULATING_OPTIMAL_PATH...",
  },
  {
    id: "line-7",
    tone: "accent",
    text: "> Routing via multi-hop aggregator and vault adapter",
  },
  {
    id: "line-8",
    tone: "accent",
    text: "> Preparing execution bundle for sequencer inclusion",
  },
  {
    id: "line-9",
    tone: "success",
    text: "✓ Strategy queued for execution window T+1 block",
  },
];

export function getVaultById(id: string | undefined) {
  return vaults.find((vault) => vault.id === id) ?? vaults[0];
}
